const nameList = [
  "Time",
  "Past",
  "Future",
  "Dev",
  "Fly",
  "Flying",
  "Soar",
  "Soaring",
  "Power",
  "Falling",
  "Fall",
  "Jump",
  "Cliff",
  "Mountain",
  "Rend",
  "Red",
  "Blue",
  "Green",
  "Yellow",
  "Gold",
  "Demon",
  "Demonic",
  "Panda",
  "Cat",
  "Kitty",
  "Kitten",
  "Zero",
  "Memory",
  "Trooper",
  "XX",
  "Bandit",
  "Fear",
  "Light",
  "Glow",
  "Tread",
  "Deep",
  "Deeper",
  "Deepest",
  "Mine",
  "Your",
  "Worst",
  "Enemy",
  "Hostile",
  "Force",
  "Video",
  "Game",
  "Donkey",
  "Mule",
  "Colt",
  "Cult",
  "Cultist",
  "Magnum",
  "Gun",
  "Assault",
  "Recon",
  "Trap",
  "Trapper",
  "Redeem",
  "Code",
  "Script",
  "Writer",
  "Near",
  "Close",
  "Open",
  "Cube",
  "Circle",
  "Geo",
  "Genome",
  "Germ",
  "Spaz",
  "Shot",
  "Echo",
  "Beta",
  "Alpha",
  "Gamma",
  "Omega",
  "Seal",
  "Squid",
  "Money",
  "Cash",
  "Lord",
  "King",
  "Duke",
  "Rest",
  "Fire",
  "Flame",
  "Morrow",
  "Break",
  "Breaker",
  "Numb",
  "Ice",
  "Cold",
  "Rotten",
  "Sick",
  "Sickly",
  "Janitor",
  "Camel",
  "Rooster",
  "Sand",
  "Desert",
  "Dessert",
  "Hurdle",
  "Racer",
  "Eraser",
  "Erase",
  "Big",
  "Small",
  "Short",
  "Tall",
  "Sith",
  "Bounty",
  "Hunter",
  "Cracked",
  "Broken",
  "Sad",
  "Happy",
  "Joy",
  "Joyful",
  "Crimson",
  "Destiny",
  "Deceit",
  "Lies",
  "Lie",
  "Honest",
  "Destined",
  "Bloxxer",
  "Hawk",
  "Eagle",
  "Hawker",
  "Walker",
  "Zombie",
  "Sarge",
  "Capt",
  "Captain",
  "Punch",
  "One",
  "Two",
  "Uno",
  "Slice",
  "Slash",
  "Melt",
  "Melted",
  "Melting",
  "Fell",
  "Wolf",
  "Hound",
  "Legacy",
  "Sharp",
  "Dead",
  "Mew",
  "Chuckle",
  "Bubba",
  "Bubble",
  "Sandwich",
  "Smasher",
  "Extreme",
  "Multi",
  "Universe",
  "Ultimate",
  "Death",
  "Ready",
  "Monkey",
  "Elevator",
  "Wrench",
  "Grease",
  "Head",
  "Theme",
  "Grand",
  "Cool",
  "Kid",
  "Boy",
  "Girl",
  "Vortex",
  "Paradox",
];

const messageList = [
  "“You know you’re in love when you can’t fall asleep because reality is finally better than your dreams.” —Dr. Suess",
  "“Love yourself first and everything else falls into line. You really have to love yourself to get anything done in this world.” —Lucille Ball",
  "“Let us always meet each other with smile, for the smile is the beginning of love.” —Mother Teresa",
  "“It is not a lack of love, but a lack of friendship that makes unhappy marriages.” —Friedrich Nietzsche",
  "“Love is that condition in which the happiness of another person is essential to your own.” —Robert A. Heinlein",
  "“The best thing to hold onto in life is each other.” —Audrey Hepburn",
  "“You know it’s love when all you want is that person to be happy, even if you’re not part of their happiness. —Julia Roberts",
  "“You always gain by giving love.” Reese Witherspoon",
  "“I love her, and that’s the beginning and end of everything.” —F. Scott Fitzgerald",
  "“Love is composed of a single soul inhabiting two bodies.” —Aristotle",
  "“Love is friendship that has caught fire.” —Ann Landers",
  "“To be brave is to love someone unconditionally, without expecting anything in return.” —Madonna",
  "“Keep love in your heart. A life without it is like a sunless garden when the flowers are dead.” —Oscar Wilde",
  "“The more I think it over, the more I feel that there is nothing more truly artistic than to love people.” —Vincent van Gogh",
  "“There is no charm equal to tenderness of heart”. —Jane Austen",
  "“You can’t blame gravity for falling in love.” —Albert Einstein”",
  "“The real lover is the man who can thrill you just by touching your head or smiling into your eyes — or just by staring into space.” —Marilyn Monroe",
  "“True love stories never have endings.” —Richard Bach",
  "“Tis better to have loved and lost, than never to have loved at all.” —Alfred, Lord Tennyson",
  "“To feel the love of people whom we love is a fire that feeds our life.” —Pablo Neruda",
];

export function generateRandomName() {
  return nameList[Math.floor(Math.random() * nameList.length)];
}

export function generateRandomMessgae() {
  return messageList[Math.floor(Math.random() * messageList.length)];
}
